---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Deploy Updated Web App on RHEL
      condition: event.payload.repository.url is match("git://github.com/nmartins0611/evs-rhel-app")
      action:
        run_job_template:
        organization: "Default"
        name: "Deploy Web App RHEL"
