---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Deploy Updated Web App on RHEL
      condition: event.payload.name is match("RHEL APP Update")
      action:
        run_job_template:
        organization: "Default"
        name: "Deploy Web App RHEL"
